-- tables
-- Table: Chat_conversation
CREATE TABLE Chat_conversation (
                                   Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                   Created_at timestamp  NOT NULL,
                                   Trade_Id int  NOT NULL,
                                   Closed_at timestamptz  NULL,
                                   CONSTRAINT Chat_conversation_pk PRIMARY KEY (Id)
);

-- Table: Chat_messages
CREATE TABLE Chat_messages (
                               Id bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               Chat_conversation_Id int  NOT NULL,
                               Sender_Id int  NOT NULL,
                               Message text  NOT NULL,
                               Created_at timestamp  NOT NULL,
                               Edited_at timestamp  NULL,
                               Deleted_at timestamp  NULL,
                               CONSTRAINT Chat_messages_pk PRIMARY KEY (Id,Chat_conversation_Id)
);

-- Table: Conversation_member
CREATE TABLE Conversation_member (
                                     User_Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                     Chat_conversation_Id int  NOT NULL,
                                     Last_read_message_id bigint  NULL,
                                     Last_read_message_chat_conversation_id int  NULL,
                                     CONSTRAINT Conversation_member_pk PRIMARY KEY (User_Id,Chat_conversation_Id)
);

-- Table: Counter_Offer
CREATE TABLE Counter_Offer (
                               Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               User_Id int  NOT NULL,
                               Creation_Date timestamptz  NOT NULL,
                               Tokens_Offered int  NOT NULL,
                               Counter_offer_Status_Id int  NOT NULL,
                               Offer_Id int  NOT NULL,
                               CONSTRAINT ListingOffer_pk PRIMARY KEY (Id)
);

-- Table: Counter_Offer_Status
CREATE TABLE Counter_Offer_Status (
                                      Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                      Status_Name varchar(50)  NOT NULL,
                                      CONSTRAINT Status_pk PRIMARY KEY (Id)
);

-- Table: Emails
CREATE TABLE Emails (
                        Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                        User_Id int  NOT NULL,
                        Subject varchar(200)  NOT NULL,
                        Body varchar(10000)  NOT NULL,
                        Created_at timestamp  NOT NULL,
                        Sent_at timestamp  NULL,
                        CONSTRAINT Emails_pk PRIMARY KEY (Id)
);

-- Table: Game
CREATE TABLE Game (
                      Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                      Name varchar(50)  NOT NULL,
                      Photo_URL varchar(2048)  NULL,
                      Genre_Id int  NOT NULL,
                      Is_Deleted boolean  NOT NULL DEFAULT false,
                      CONSTRAINT Game_pk PRIMARY KEY (Id)
);

-- Table: Genre
CREATE TABLE Genre (
                       Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                       Name varchar(20)  NOT NULL,
                       Is_Deleted boolean  NOT NULL DEFAULT false,
                       CONSTRAINT Genre_pk PRIMARY KEY (Id)
);

-- Table: Item
CREATE TABLE Item (
                      Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                      Game_Id int  NOT NULL,
                      Item_rarity_Id int  NOT NULL,
                      Name varchar(50)  NOT NULL,
                      Photo_URL varchar(2048) NULL,
                      Is_Deleted boolean  NOT NULL DEFAULT false,
                      Estimated_token_value int  NOT NULL,
                      CONSTRAINT Item_pk PRIMARY KEY (Id)
);

-- Table: Item_rarity
CREATE TABLE Item_rarity (
                             Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                             Game_Id int  NOT NULL,
                             Rarity_name varchar(20)  NOT NULL,
                             Is_Deleted boolean  NOT NULL DEFAULT false,
                             CONSTRAINT Item_rarity_pk PRIMARY KEY (Id)
);

-- Table: Listing_Counter_Offer_Items
CREATE TABLE Listing_Counter_Offer_Items (
                                             Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                             Item_Id int  NOT NULL,
                                             Counter_Offer_Id int  NOT NULL,
                                             Quantity int  NOT NULL,
                                             CONSTRAINT ListingOfferItems_pk PRIMARY KEY (Id,Counter_Offer_Id,Item_Id)
);

-- Table: Listing_Items
CREATE TABLE Listing_Items (
                               Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               Offer_Id int  NOT NULL,
                               Item_Id int  NOT NULL,
                               Quantity int  NOT NULL,
                               Is_wanted boolean  NOT NULL,
                               CONSTRAINT ListingItems_pk PRIMARY KEY (Id,Offer_Id,Item_Id)
);

-- Table: Notification
CREATE TABLE Notification (
                              Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              User_Id int  NOT NULL,
                              Title varchar(50)  NOT NULL,
                              Message varchar(400)  NOT NULL,
                              Created_at timestamptz  NOT NULL,
                              Read_at timestamptz  NULL,
                              is_deleted boolean  NOT NULL DEFAULT false,
                              CONSTRAINT Notification_pk PRIMARY KEY (Id)
);

-- Table: Offer
CREATE TABLE Offer (
                       Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                       User_Id int  NOT NULL,
                       Exp_Date date  NOT NULL,
                       Creation_date date  NOT NULL,
                       Token_Cost int  NOT NULL,
                       Offer_Status_Id int  NOT NULL,
                       Title text  NOT NULL,
                       Description text  NOT NULL,
                       Is_highlighted boolean  NOT NULL,
                       Tokens_offered int  NOT NULL,
                       Tokens_wanted int  NOT NULL,
                       CONSTRAINT Listing_pk PRIMARY KEY (Id)
);

-- Table: Offer_Status
CREATE TABLE Offer_Status (
                              Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              Status_Name varchar(50)  NOT NULL,
                              CONSTRAINT Offer_Status_pk PRIMARY KEY (Id)
);

-- Table: Profile_Info
CREATE TABLE Profile_Info (
                              User_Id int  NOT NULL,
                              Nickname varchar(20)  NOT NULL,
                              Description varchar(500)  NOT NULL,
                              Image_URL varchar(2048) NULL,
                              CONSTRAINT Profile_Info_pk PRIMARY KEY (User_Id)
);

-- Table: Rate
CREATE TABLE Rate (
                      User_Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                      Trade_Id int  NOT NULL,
                      Mark decimal(3,1)  NOT NULL,
                      Description varchar(500)  NOT NULL,
                      CONSTRAINT Rate_pk PRIMARY KEY (User_Id,Trade_Id)
);

-- Table: Trade
CREATE TABLE Trade (
                       Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                       Creation_Date timestamptz  NOT NULL,
                       Completition_Date timestamptz  NULL,
                       Trade_Status_Id int  NOT NULL,
                       Offer_Id int  NOT NULL,
                       Customer_Id int  NOT NULL,
                       Middleman_User_Id int  NULL,
                       User_Id int  NOT NULL,
                       Has_buyers_items boolean  NOT NULL,
                       Has_sellers_items boolean  NOT NULL,
                       CONSTRAINT Trade_pk PRIMARY KEY (Id)
);

-- Table: Trade_Status
CREATE TABLE Trade_Status (
                              Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              Status_Name varchar(50)  NOT NULL,
                              CONSTRAINT TradeStatus_pk PRIMARY KEY (Id)
);

-- Table: Trade_urls
CREATE TABLE Trade_urls (
                            Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                            Trade_Id int  NOT NULL,
                            Photo_url varchar(2048) NOT NULL,
                            Is_buyers boolean  NOT NULL,
                            CONSTRAINT Trade_urls_pk PRIMARY KEY (Id)
);

-- Table: User
CREATE TABLE "User" (
                        Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                        Auth0_UserId varchar(128)  NULL,
                        Stripe_Customer_Id varchar(128)  NULL,
                        Email varchar(100)  NULL,
                        Date_Of_Birth date  NOT NULL,
                        Tokens int  NOT NULL,
                        Escrowed_tokens int  NOT NULL,
                        Experience int  NOT NULL,
                        Token_Exp_Date timestamptz  NOT NULL,
                        Registration_Date date  NOT NULL,
                        Is_Deleted boolean  NOT NULL DEFAULT false,
                        CONSTRAINT User_pk PRIMARY KEY (Id)
);

-- Table: User_favourite_offer
CREATE TABLE User_favourite_offer (
                                      User_Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                      Offer_Id int  NOT NULL,
                                      Added_at timestamptz  NOT NULL,
                                      CONSTRAINT User_favourite_offer_pk PRIMARY KEY (Offer_Id,User_Id)
);

-- foreign keys
-- Reference: Chat_conversation_Trade (table: Chat_conversation)
ALTER TABLE Chat_conversation ADD CONSTRAINT Chat_conversation_Trade
    FOREIGN KEY (Trade_Id)
        REFERENCES Trade (Id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Chat_messages_Chat_conversation (table: Chat_messages)
ALTER TABLE Chat_messages ADD CONSTRAINT Chat_messages_Chat_conversation
    FOREIGN KEY (Chat_conversation_Id)
        REFERENCES Chat_conversation (Id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Chat_messages_User (table: Chat_messages)
ALTER TABLE Chat_messages ADD CONSTRAINT Chat_messages_User
    FOREIGN KEY (Sender_Id)
        REFERENCES "User" (Id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Conversation_member_Chat_conversation (table: Conversation_member)
ALTER TABLE Conversation_member ADD CONSTRAINT Conversation_member_Chat_conversation
    FOREIGN KEY (Chat_conversation_Id)
        REFERENCES Chat_conversation (Id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Conversation_member_Chat_messages (table: Conversation_member)
ALTER TABLE Conversation_member ADD CONSTRAINT Conversation_member_Chat_messages
    FOREIGN KEY (Last_read_message_id, Last_read_message_chat_conversation_id)
        REFERENCES Chat_messages (Id, Chat_conversation_Id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Conversation_member_User (table: Conversation_member)
ALTER TABLE Conversation_member ADD CONSTRAINT Conversation_member_User
    FOREIGN KEY (User_Id)
        REFERENCES "User" (Id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: CounterOffers_Offer (table: Counter_Offer)
ALTER TABLE Counter_Offer ADD CONSTRAINT CounterOffers_Offer
    FOREIGN KEY (Offer_Id)
        REFERENCES Offer (Id)
        ON DELETE  RESTRICT
        ON UPDATE  CASCADE
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Counter_offer_status_Co (table: Counter_Offer)
ALTER TABLE Counter_Offer ADD CONSTRAINT Counter_offer_status_Co
    FOREIGN KEY (Counter_offer_Status_Id)
        REFERENCES Counter_Offer_Status (Id)
        ON DELETE  RESTRICT
        ON UPDATE  CASCADE
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Game_Genre (table: Game)
ALTER TABLE Game ADD CONSTRAINT Game_Genre
    FOREIGN KEY (Genre_Id)
        REFERENCES Genre (Id)
        ON DELETE  RESTRICT
        ON UPDATE  CASCADE
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Item_Game (table: Item)
ALTER TABLE Item ADD CONSTRAINT Item_Game
    FOREIGN KEY (Game_Id)
        REFERENCES Game (Id)
        ON DELETE  RESTRICT
        ON UPDATE  CASCADE
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Item_Item_rarity (table: Item)
ALTER TABLE Item ADD CONSTRAINT Item_Item_rarity
    FOREIGN KEY (Item_rarity_Id)
        REFERENCES Item_rarity (Id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Item_rarity_Game (table: Item_rarity)
ALTER TABLE Item_rarity ADD CONSTRAINT Item_rarity_Game
    FOREIGN KEY (Game_Id)
        REFERENCES Game (Id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: ListingItems_Item (table: Listing_Items)
ALTER TABLE Listing_Items ADD CONSTRAINT ListingItems_Item
    FOREIGN KEY (Item_Id)
        REFERENCES Item (Id)
        ON DELETE  RESTRICT
        ON UPDATE  CASCADE
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: ListingOfferItems_Item (table: Listing_Counter_Offer_Items)
ALTER TABLE Listing_Counter_Offer_Items ADD CONSTRAINT ListingOfferItems_Item
    FOREIGN KEY (Item_Id)
        REFERENCES Item (Id)
        ON DELETE  RESTRICT
        ON UPDATE  CASCADE
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: ListingOffer_User (table: Counter_Offer)
ALTER TABLE Counter_Offer ADD CONSTRAINT ListingOffer_User
    FOREIGN KEY (User_Id)
        REFERENCES "User" (Id)
        ON DELETE  RESTRICT
        ON UPDATE  CASCADE
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Listing_Counter_Offer_Items_Counter_Offer (table: Listing_Counter_Offer_Items)
ALTER TABLE Listing_Counter_Offer_Items ADD CONSTRAINT Listing_Counter_Offer_Items_Counter_Offer
    FOREIGN KEY (Counter_Offer_Id)
        REFERENCES Counter_Offer (Id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Listing_Items_Offer (table: Listing_Items)
ALTER TABLE Listing_Items ADD CONSTRAINT Listing_Items_Offer
    FOREIGN KEY (Offer_Id)
        REFERENCES Offer (Id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Listing_User (table: Offer)
ALTER TABLE Offer ADD CONSTRAINT Listing_User
    FOREIGN KEY (User_Id)
        REFERENCES "User" (Id)
        ON DELETE  RESTRICT
        ON UPDATE  CASCADE
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Offer_Offer_Status (table: Offer)
ALTER TABLE Offer ADD CONSTRAINT Offer_Offer_Status
    FOREIGN KEY (Offer_Status_Id)
        REFERENCES Offer_Status (Id)
        ON DELETE  RESTRICT
        ON UPDATE  CASCADE
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: ProfileInfo_User (table: Profile_Info)
ALTER TABLE Profile_Info ADD CONSTRAINT ProfileInfo_User
    FOREIGN KEY (User_Id)
        REFERENCES "User" (Id)
        ON DELETE  RESTRICT
        ON UPDATE  CASCADE
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Rate_Trade (table: Rate)
ALTER TABLE Rate ADD CONSTRAINT Rate_Trade
    FOREIGN KEY (Trade_Id)
        REFERENCES Trade (Id)
        ON DELETE  RESTRICT
        ON UPDATE  CASCADE
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Rate_User (table: Rate)
ALTER TABLE Rate ADD CONSTRAINT Rate_User
    FOREIGN KEY (User_Id)
        REFERENCES "User" (Id)
        ON DELETE  RESTRICT
        ON UPDATE  CASCADE
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Table_35_Trade (table: Trade_urls)
ALTER TABLE Trade_urls ADD CONSTRAINT Table_35_Trade
    FOREIGN KEY (Trade_Id)
        REFERENCES Trade (Id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Table_36_User (table: Notification)
ALTER TABLE Notification ADD CONSTRAINT Table_36_User
    FOREIGN KEY (User_Id)
        REFERENCES "User" (Id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Table_42_Offer (table: User_favourite_offer)
ALTER TABLE User_favourite_offer ADD CONSTRAINT Table_42_Offer
    FOREIGN KEY (Offer_Id)
        REFERENCES Offer (Id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Table_42_User (table: User_favourite_offer)
ALTER TABLE User_favourite_offer ADD CONSTRAINT Table_42_User
    FOREIGN KEY (User_Id)
        REFERENCES "User" (Id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Trade_Listing (table: Trade)
ALTER TABLE Trade ADD CONSTRAINT Trade_Listing
    FOREIGN KEY (Offer_Id)
        REFERENCES Offer (Id)
        ON DELETE  RESTRICT
        ON UPDATE  CASCADE
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Trade_Middleman (table: Trade)
ALTER TABLE Trade ADD CONSTRAINT Trade_Middleman
    FOREIGN KEY (Middleman_User_Id)
        REFERENCES "User" (Id)
        ON DELETE  RESTRICT
        ON UPDATE  CASCADE
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Trade_TradeStatus (table: Trade)
ALTER TABLE Trade ADD CONSTRAINT Trade_TradeStatus
    FOREIGN KEY (Trade_Status_Id)
        REFERENCES Trade_Status (Id)
        ON DELETE  RESTRICT
        ON UPDATE  CASCADE
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Trade_User (table: Trade)
ALTER TABLE Trade ADD CONSTRAINT Trade_User
    FOREIGN KEY (Customer_Id)
        REFERENCES "User" (Id)
        ON DELETE  RESTRICT
        ON UPDATE  CASCADE
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: User_buyer (table: Trade)
ALTER TABLE Trade ADD CONSTRAINT User_buyer
    FOREIGN KEY (User_Id)
        REFERENCES "User" (Id)
        ON DELETE  RESTRICT
        ON UPDATE  CASCADE
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: User_emails_User (table: Emails)
ALTER TABLE Emails ADD CONSTRAINT User_emails_User
    FOREIGN KEY (User_Id)
        REFERENCES "User" (Id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Unique Index
CREATE UNIQUE INDEX IF NOT EXISTS uq_item_game_name_active
    ON item(Game_id, Name)
    WHERE is_deleted = false;

CREATE UNIQUE INDEX IF NOT EXISTS uq_item_rarity_game_name_active
    ON item_rarity(Game_id, Rarity_name)
    WHERE is_deleted = false;

CREATE UNIQUE INDEX IF NOT EXISTS uq_genre_name_active
    ON genre(Name)
    WHERE is_deleted = false;

CREATE UNIQUE INDEX IF NOT EXISTS uq_game_name_active
    ON game(Name)
    WHERE is_deleted = false;

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_email
    ON "User"(Email);

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_auth0
    ON "User"(Auth0_UserId);

-- Selected FK
--Trade

CREATE INDEX IF NOT EXISTS ix_trade_customer
    ON trade(Customer_Id);

CREATE INDEX IF NOT EXISTS ix_trade_middleman_status
    ON trade(Middleman_User_Id, Trade_status_id);

CREATE INDEX IF NOT EXISTS ix_trade_offer_status
    ON trade(Offer_id, Trade_status_id);

CREATE INDEX IF NOT EXISTS ix_trade_status_creation
    ON trade(Trade_status_id, Creation_Date);

--ListingItems
CREATE INDEX IF NOT EXISTS ix_listing_items_offer_wanted
    ON listing_items(Offer_Id, Is_wanted);

CREATE INDEX IF NOT EXISTS ix_listing_items_item_id
    ON listing_items(Item_Id);

--CounterOffer
CREATE INDEX IF NOT EXISTS ix_counter_offer_offer_status
    ON counter_offer(Offer_Id, Counter_offer_Status_Id);

CREATE INDEX IF NOT EXISTS ix_counter_offer_user_created
    ON counter_offer(User_Id, Creation_Date);

--Offer
CREATE INDEX IF NOT EXISTS ix_offer_user_status
    ON offer(User_Id, Offer_Status_Id);

--FavouriteOffer
CREATE INDEX IF NOT EXISTS ix_user_favourite_offer_user_added
    ON User_favourite_offer(User_Id, Added_at DESC);

--Notification
CREATE INDEX IF NOT EXISTS ix_notification_created
    ON notification(User_Id, Created_at DESC, Id DESC)
    WHERE is_deleted = false;

--Item
CREATE INDEX IF NOT EXISTS ix_item_item_rarity
    ON item(Item_rarity_id)
    WHERE is_deleted = false;

--Listing CounterOffer Items
CREATE INDEX IF NOT EXISTS ix_listing_counter_offer_id
    ON listing_counter_offer_items(counter_offer_id);

--Chat
CREATE INDEX IF NOT EXISTS ix_chat_conversation_trade
    ON chat_conversation(Trade_id);

CREATE INDEX IF NOT EXISTS ix_chat_messages_chat_conversation_id
    ON chat_messages(Chat_conversation_id, Id DESC);

CREATE INDEX IF NOT EXISTS ix_conversation_member_chat_conversation_id
    ON conversation_member(Chat_conversation_Id);

--Trade_urls
CREATE INDEX IF NOT EXISTS  ix_trade_urls_trade_id
    ON trade_urls(Trade_Id);


--ILike search GIN index
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX IF NOT EXISTS ix_item_name
    ON item USING GIN (Name gin_trgm_ops)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS ix_profile_info_nickname
    ON profile_info USING GIN (Nickname gin_trgm_ops);

CREATE INDEX IF NOT EXISTS ix_user_email
    ON "User" USING GIN (Email gin_trgm_ops);

--Active offer browsing
CREATE INDEX IF NOT EXISTS ix_offer_active_created
    ON offer (Creation_date) WHERE offer_status_id = 1;

CREATE INDEX IF NOT EXISTS ix_offer_active_exp
    ON offer (Exp_Date) WHERE offer_status_id = 1;

CREATE INDEX IF NOT EXISTS ix_offer_active_token_cost
    ON offer (Token_Cost) WHERE offer_status_id = 1;

--Unread notifcations
CREATE INDEX IF NOT EXISTS ix_notifications_unread
    ON notification (User_id) WHERE read_at IS NULL AND is_deleted = false;

--Rating

CREATE INDEX IF NOT EXISTS ix_rate_user 
    ON rate(User_Id, Mark);

--Business index
CREATE UNIQUE INDEX uq_trade_offer_id_active
    ON trade(Offer_id) WHERE trade_status_id != 4;

--Alters

ALTER TABLE trade
    ADD counter_offer_id int NULL;

ALTER TABLE trade
    ADD CONSTRAINT FK_trade_counter_offer
        FOREIGN KEY (counter_offer_id)
            REFERENCES counter_offer(id);

ALTER TABLE trade
    DROP CONSTRAINT user_buyer;
         
ALTER TABLE trade
    DROP COLUMN user_id;
-- End of file.